# Generated by Django 3.0.2 on 2020-01-28 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drawnings', '0002_drawning_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawning',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drawnings', to=settings.AUTH_USER_MODEL),
        ),
    ]
